language: php
php:
  - 5.5
  - 5.4
  - 5.3

before_script:
  - composer self-update && composer --version
  - composer install

script: phpunit --coverage-text --configuration tests/phpunit.xml

notifications:
  email:
    - dev@funivan.com